### ISSUE TITLE
Plugin does not work with Kibana 7.4.0

### ISSUE THREAD

**Issue by roniez** [novomatic-tech/keycloak-kibana#32]
When building the plugin towards the 7.4.0 version of kibana i get the following error when loading the plugin.

```
{"type":"log","@timestamp":"2019-10-24T11:30:56Z","tags":["fatal","root"],"pid":6,"message":"{ Error: Optimizations failure.\n   6712 modules\n    \n    ERROR in /plugins/kibana/keycloak-kibana/public/views/nav_control/nav_control.js\n    Module not found: Error: Can't resolve 'ui/chrome/directives/header_global_nav' in '/plugins/kibana/keycloak-kibana/public/views/nav_control'\n    \n    ERROR in /plugins/kibana/keycloak-kibana/public/authz/decorations/HeaderGlobalNavDecorator.js\n    Module not found: Error: Can't resolve 'ui/chrome/directives/header_global_nav/components/header' in '/plugins/kibana/keycloak-kibana/public/authz/decorations'\n\n    at FsOptimizer.failedStatsToError (/usr/share/kibana/src/optimize/base_optimizer.js:438:26)\n    at compiler.run (/usr/share/kibana/src/optimize/fs_optimizer.js:43:26)\n    at finalCallback (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:257:39)\n    at hooks.done.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:273:13)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)\n    at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n    at onCompiled (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:271:21)\n    at hooks.afterCompile.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:671:15)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)\n    at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n    at compilation.seal.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:668:31)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n    at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n    at hooks.optimizeAssets.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:1385:35)\n    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n    at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n  cause:\n   { Error: Optimizations failure.\n      6712 modules\n       \n       ERROR in /plugins/kibana/keycloak-kibana/public/views/nav_control/nav_control.js\n       Module not found: Error: Can't resolve 'ui/chrome/directives/header_global_nav' in '/plugins/kibana/keycloak-kibana/public/views/nav_control'\n       \n       ERROR in /plugins/kibana/keycloak-kibana/public/authz/decorations/HeaderGlobalNavDecorator.js\n       Module not found: Error: Can't resolve 'ui/chrome/directives/header_global_nav/components/header' in '/plugins/kibana/keycloak-kibana/public/authz/decorations'\n   \n       at FsOptimizer.failedStatsToError (/usr/share/kibana/src/optimize/base_optimizer.js:438:26)\n       at compiler.run (/usr/share/kibana/src/optimize/fs_optimizer.js:43:26)\n       at finalCallback (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:257:39)\n       at hooks.done.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:273:13)\n       at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)\n       at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n       at onCompiled (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:271:21)\n       at hooks.afterCompile.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:671:15)\n       at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)\n       at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n       at compilation.seal.err (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:668:31)\n       at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n       at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n       at hooks.optimizeAssets.callAsync.err (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:1385:35)\n       at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/share/kibana/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n       at AsyncSeriesHook.lazyCompileHook (/usr/share/kibana/node_modules/tapable/lib/Hook.js:154:20)\n     data:\n      { errors: [Array],\n        warnings: [],\n        version: '4.39.2',\n        hash: 'b1d7ef06f61880f6256f',\n        time: 190097,\n        builtAt: 1571916655350,\n        publicPath: '__REPLACE_WITH_PUBLIC_PATH__',\n        outputPath: '/usr/share/kibana/optimize/bundles',\n        assetsByChunkName: [Object],\n        assets: [Array],\n        filteredAssets: 0,\n        entrypoints: [Object],\n        namedChunkGroups: [Object],\n        chunks: [Array],\n        modules: [Array],\n        filteredModules: 0,\n        logging: [Object],\n        children: [Array] },\n     isBoom: true,\n     isServer: true,\n     output: { statusCode: 500, payload: [Object], headers: {} },\n     reformat: [Function],\n     typeof: [Function: internal] },\n  isOperational: true,\n  data:\n   { errors:\n      [ '/plugins/kibana/keycloak-kibana/public/views/nav_control/nav_control.js\\nModule not found: Error: Can\\'t resolve \\'ui/chrome/directives/header_global_nav\\' in \\'/plugins/kibana/keycloak-kibana/public/views/nav_control\\'\\nresolve \\'ui/chrome/directives/header_global_nav\\' in \\'/plugins/kibana/keycloak-kibana/public/views/nav_control\\'\\n  Parsed request is a module\\n  using description file: /plugins/kibana/keycloak-kibana/package.json (relative path: ./public/views/nav_control)\\n    aliased with mapping \\'ui\\': \\'/usr/share/kibana/src/legacy/ui/public\\' to \\'/usr/share/kibana/src/legacy/ui/public/chrome/directives/header_global_nav\\'\\n      using description file: /plugins/kibana/keycloak-kibana/package.json (relative path: ./public/views/nav_control)\\n        Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n        using description file: /usr/share/kibana/package.json (relative path: ./src/legacy/ui/public/chrome/directives/header_global_nav)\\n          no extension\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/legacy/ui/public/chrome/directives/header_global_nav doesn\\'t exist\\n          .js\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/legacy/ui/public/chrome/directives/header_global_nav.js doesn\\'t exist\\n          .ts\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/legacy/ui/public/chrome/directives/header_global_nav.ts doesn\\'t exist\\n          .tsx\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/legacy/ui/public/chrome/directives/header_global_nav.tsx doesn\\'t exist\\n          .json\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/legacy/ui/public/chrome/directives/header_global_nav.json doesn\\'t exist\\n          as directory\\n            /usr/share/kibana/src/legacy/ui/public/chrome/directives/header_global_nav doesn\\'t exist\\n[/usr/share/kibana/src/legacy/ui/public/chrome/directives/header_global_nav]\\n[/usr/share/kibana/src/legacy/ui/public/chrome/directives/header_global_nav.js]\\n[/usr/share/kibana/src/legacy/ui/public/chrome/directives/header_global_nav.ts]\\n[/usr/share/kibana/src/legacy/ui/public/chrome/directives/header_global_nav.tsx]\\n[/usr/share/kibana/src/legacy/ui/public/chrome/directives/header_global_nav.json]\\n @ /plugins/kibana/keycloak-kibana/public/views/nav_control/nav_control.js 11:25-74\\n @ /plugins/kibana/keycloak-kibana/public/views/nav_control/index.js\\n @ ./node_modules/val-loader/dist/cjs.js!./src/optimize/create_ui_exports_module.js?{\"type\":\"chromeNavControls\",\"modules\":[\"plugins/keycloak-kibana/views/nav_control\",\"plugins/spaces/views/nav_control\"]}\\n @ ./src/legacy/ui/public/chrome/chrome.js\\n @ ./src/legacy/ui/public/chrome/index.js\\n @ ./src/legacy/core_plugins/status_page/public/status_page.js\\n @ ./optimize/bundles/status_page.entry.js',\n        '/plugins/kibana/keycloak-kibana/public/authz/decorations/HeaderGlobalNavDecorator.js\\nModule not found: Error: Can\\'t resolve \\'ui/chrome/directives/header_global_nav/components/header\\' in \\'/plugins/kibana/keycloak-kibana/public/authz/decorations\\'\\nresolve \\'ui/chrome/directives/header_global_nav/components/header\\' in \\'/plugins/kibana/keycloak-kibana/public/authz/decorations\\'\\n  Parsed request is a module\\n  using description file: /plugins/kibana/keycloak-kibana/package.json (relative path: ./public/authz/decorations)\\n    aliased with mapping \\'ui\\': \\'/usr/share/kibana/src/legacy/ui/public\\' to \\'/usr/share/kibana/src/legacy/ui/public/chrome/directives/header_global_nav/components/header\\'\\n      using description file: /plugins/kibana/keycloak-kibana/package.json (relative path: ./public/authz/decorations)\\n        Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n        using description file: /usr/share/kibana/package.json (relative path: ./src/legacy/ui/public/chrome/directives/header_global_nav/components/header)\\n          no extension\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/legacy/ui/public/chrome/directives/header_global_nav/components/header doesn\\'t exist\\n          .js\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/legacy/ui/public/chrome/directives/header_global_nav/components/header.js doesn\\'t exist\\n          .ts\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/legacy/ui/public/chrome/directives/header_global_nav/components/header.ts doesn\\'t exist\\n          .tsx\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/legacy/ui/public/chrome/directives/header_global_nav/components/header.tsx doesn\\'t exist\\n          .json\\n            Field \\'browser\\' doesn\\'t contain a valid alias configuration\\n            /usr/share/kibana/src/legacy/ui/public/chrome/directives/header_global_nav/components/header.json doesn\\'t exist\\n          as directory\\n            /usr/share/kibana/src/legacy/ui/public/chrome/directives/header_global_nav/components/header doesn\\'t exist\\n[/usr/share/kibana/src/legacy/ui/public/chrome/directives/header_global_nav/components/header]\\n[/usr/share/kibana/src/legacy/ui/public/chrome/directives/header_global_nav/components/header.js]\\n[/usr/share/kibana/src/legacy/ui/public/chrome/directives/header_global_nav/components/header.ts]\\n[/usr/share/kibana/src/legacy/ui/public/chrome/directives/header_global_nav/components/header.tsx]\\n[/usr/share/kibana/src/legacy/ui/public/chrome/directives/header_global_nav/components/header.json]\\n @ /plugins/kibana/keycloak-kibana/public/authz/decorations/HeaderGlobalNavDecorator.js 10:14-81\\n @ /plugins/kibana/keycloak-kibana/public/authz/index.js\\n @ /plugins/kibana/keycloak-kibana/public/views/nav_control/index.js\\n @ ./node_modules/val-loader/dist/cjs.js!./src/optimize/create_ui_exports_module.js?{\"type\":\"chromeNavControls\",\"modules\":[\"plugins/keycloak-kibana/views/nav_control\",\"plugins/spaces/views/nav_control\"]}\\n @ ./src/legacy/ui/public/chrome/chrome.js\\n @ ./src/legacy/ui/public/chrome/index.js\\n @ ./src/legacy/core_plugins/status_page/public/status_page.js\\n @ ./optimize/bundles/status_page.entry.js' ],\n     warnings: [],\n     version: '4.39.2',\n     hash: 'b1d7ef06f61880f6256f',\n     time: 190097,\n     builtAt: 1571916655350,\n     publicPath: '__REPLACE_WITH_PUBLIC_PATH__',\n     outputPath: '/usr/share/kibana/optimize/bundles',\n     assetsByChunkName:\n      { commons: [Array],\n        canvas: [Array],\n        code: [Array],\n        dark_theme: [Array],\n        dashboardViewer: 'dashboardViewer.bundle.js',\n        graph: 'graph.bundle.js',\n        infra: 'infra.bundle.js',\n        kibana: [Array],\n        light_theme: [Array],\n        maps: 'maps.bundle.js',\n        monitoring: [Array],\n        'plugin/data': 'plugin/data.bundle.js',\n        'plugin/inspector': 'plugin/inspector.bundle.js',\n        siem: 'siem.bundle.js',\n        space_selector: 'space_selector.bundle.js',\n        stateSessionStorageRedirect: 'stateSessionStorageRedirect.bundle.js',\n        status_page: 'status_page.bundle.js',\n        timelion: 'timelion.bundle.js',\n        uptime: 'uptime.bundle.js' },\n     assets:\n      [ [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object] ],\n     filteredAssets: 0,\n     entrypoints:\n      { graph: [Object],\n        monitoring: [Object],\n        space_selector: [Object],\n        dashboardViewer: [Object],\n        code: [Object],\n        maps: [Object],\n        canvas: [Object],\n        infra: [Object],\n        siem: [Object],\n        uptime: [Object],\n        kibana: [Object],\n        stateSessionStorageRedirect: [Object],\n        status_page: [Object],\n        timelion: [Object],\n        'plugin/inspector': [Object],\n        'plugin/data': [Object],\n        light_theme: [Object],\n        dark_theme: [Object] },\n     namedChunkGroups:\n      { graph: [Object],\n        monitoring: [Object],\n        space_selector: [Object],\n        dashboardViewer: [Object],\n        code: [Object],\n        maps: [Object],\n        canvas: [Object],\n        infra: [Object],\n        siem: [Object],\n        uptime: [Object],\n        kibana: [Object],\n        stateSessionStorageRedirect: [Object],\n        status_page: [Object],\n        timelion: [Object],\n        'plugin/inspector': [Object],\n        'plugin/data': [Object],\n        light_theme: [Object],\n        dark_theme: [Object] },\n     chunks:\n      [ [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object] ],\n     modules:\n      [ [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        ... 6612 more items ],\n     filteredModules: 0,\n     logging: { 'webpack.buildChunkGraph.visitModules': [Object] },\n     children:\n      [ [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object],\n        [Object] ] },\n  isBoom: true,\n  isServer: true,\n  output:\n   { statusCode: 500,\n     payload:\n      { statusCode: 500,\n        error: 'Internal Server Error',\n        message: 'An internal server error occurred' },\n     headers: {} },\n  reformat: [Function],\n  typeof: [Function: internal] }"}
{"type":"log","@timestamp":"2019-10-24T11:30:56Z","tags":["info","plugins-system"],"pid":6,"message":"Stopping all plugins."}
{"type":"log","@timestamp":"2019-10-24T11:30:56Z","tags":["info","plugins","data"],"pid":6,"message":"Stopping plugin"}
{"type":"log","@timestamp":"2019-10-24T11:30:56Z","tags":["info","plugins","translations"],"pid":6,"message":"Stopping plugin"}
 FATAL  Error: Optimizations failure.
   6712 modules

    ERROR in /plugins/kibana/keycloak-kibana/public/views/nav_control/nav_control.js
    Module not found: Error: Can't resolve 'ui/chrome/directives/header_global_nav' in '/plugins/kibana/keycloak-kibana/public/views/nav_control'

    ERROR in /plugins/kibana/keycloak-kibana/public/authz/decorations/HeaderGlobalNavDecorator.js
    Module not found: Error: Can't resolve 'ui/chrome/directives/header_global_nav/components/header' in '/plugins/kibana/keycloak-kibana/public/authz/decorations'
```

**Comment by Finu** [comment]
Hi @roniez  - we've updated  [keycloack-kibana](https://github.com/novomatic-tech/keycloak-kibana/releases/tag/3.1.0)  to work with kibana 7.4.2.
