### ISSUE TITLE
FATAL  TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by prasus** [novomatic-tech/keycloak-kibana#39]
Greetings!

I am facing difficulties in enabling this plugin, kibana pod fails with below error during boot-up

`FATAL  TypeError: Cannot read property 'name' of undefined`

Please find the detailed logs and other details furnished below, appreciate if you could share some pointers on fixing this. thanks. 

**env:**
```
ES/Kibana version: v7.5.0 (community edition, deployed on Kubernetes using helm chart)
keycloak-kibana version: v3.2.0 (stable release)
```

**kibana.yml**
```
server.name: kibana
server.host: "0"
elasticsearch.hosts: [ "http://es-master:9200" ]
xpack.monitoring.ui.container.elasticsearch.enabled: false
keycloak.serverUrl: https://keycloak.qa.dev/auth
keycloak.realm: ssoapps
keycloak.clientId: zoom
keycloak.clientSecret: 3ef4dfc2-e2f0-412a-b84e-126a4a48113
xpack.security.enabled: false
```

**logs**

```
{"type":"log","@timestamp":"2020-03-12T08:34:12Z","tags":["info","plugins-service"],"pid":6,"message":"Plugin \"security\" is disabled."}
{"type":"log","@timestamp":"2020-03-12T08:34:12Z","tags":["info","plugins-system"],"pid":6,"message":"Setting up [14] plugins: [code,licensing,timelion,features,spaces,translations,uiActions,inspector,embeddable,advancedUiActions,newsfeed,eui_utils,expressions,data]"}
{"type":"log","@timestamp":"2020-03-12T08:34:12Z","tags":["info","plugins","code"],"pid":6,"message":"Setting up plugin"}
{"type":"log","@timestamp":"2020-03-12T08:34:12Z","tags":["info","plugins","licensing"],"pid":6,"message":"Setting up plugin"}
{"type":"log","@timestamp":"2020-03-12T08:34:12Z","tags":["info","plugins","timelion"],"pid":6,"message":"Setting up plugin"}
{"type":"log","@timestamp":"2020-03-12T08:34:12Z","tags":["info","plugins","features"],"pid":6,"message":"Setting up plugin"}
{"type":"log","@timestamp":"2020-03-12T08:34:12Z","tags":["info","plugins","spaces"],"pid":6,"message":"Setting up plugin"}
{"type":"log","@timestamp":"2020-03-12T08:34:12Z","tags":["info","plugins","translations"],"pid":6,"message":"Setting up plugin"}
{"type":"log","@timestamp":"2020-03-12T08:34:12Z","tags":["info","plugins","data"],"pid":6,"message":"Setting up plugin"}
{"type":"log","@timestamp":"2020-03-12T08:34:26Z","tags":["warning","legacy-plugins"],"pid":6,"path":"/usr/share/kibana/src/legacy/core_plugins/visualizations","message":"Skipping non-plugin directory at /usr/share/kibana/src/legacy/core_plugins/visualizations"}
{"type":"log","@timestamp":"2020-03-12T08:34:27Z","tags":["info","plugins","licensing"],"pid":6,"message":"Imported changed license information from Elasticsearch for the [data] cluster: type: basic | status: active"}
{"type":"log","@timestamp":"2020-03-12T08:34:27Z","tags":["info","plugins-system"],"pid":6,"message":"Starting [7] plugins: [code,licensing,timelion,features,spaces,translations,data]"}
{"type":"log","@timestamp":"2020-03-12T08:34:28Z","tags":["info","optimize"],"pid":6,"message":"Optimizing and caching bundles for core, graph, monitoring, space_selector, ml, dashboardViewer, apm, maps, canvas, infra, siem, uptime, lens, kibana, stateSessionStorageRedirect, status_page and timelion. This may take a few minutes"}
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["info","optimize"],"pid":6,"message":"Optimization of bundles for core, graph, monitoring, space_selector, ml, dashboardViewer, apm, maps, canvas, infra, siem, uptime, lens, kibana, stateSessionStorageRedirect, status_page and timelion complete in 51.69 seconds"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:kibana@7.5.0","info"],"pid":6,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:elasticsearch@7.5.0","info"],"pid":6,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:xpack_main@7.5.0","info"],"pid":6,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:graph@7.5.0","info"],"pid":6,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:monitoring@7.5.0","info"],"pid":6,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:spaces@7.5.0","info"],"pid":6,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:searchprofiler@7.5.0","info"],"pid":6,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:ml@7.5.0","info"],"pid":6,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:tilemap@7.5.0","info"],"pid":6,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:watcher@7.5.0","info"],"pid":6,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:grokdebugger@7.5.0","info"],"pid":6,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:dashboard_mode@7.5.0","info"],"pid":6,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:logstash@7.5.0","info"],"pid":6,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:beats_management@7.5.0","info"],"pid":6,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:apm_oss@7.5.0","info"],"pid":6,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:apm@7.5.0","info"],"pid":6,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:interpreter@7.5.0","info"],"pid":6,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:expressions@7.5.0","info"],"pid":6,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:maps@7.5.0","info"],"pid":6,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:canvas@7.5.0","info"],"pid":6,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:license_management@7.5.0","info"],"pid":6,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:cloud@7.5.0","info"],"pid":6,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:index_management@7.5.0","info"],"pid":6,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:console@7.5.0","info"],"pid":6,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:console_extensions@7.5.0","info"],"pid":6,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:index_lifecycle_management@7.5.0","info"],"pid":6,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:kuery_autocomplete@7.5.0","info"],"pid":6,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:metrics@7.5.0","info"],"pid":6,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:infra@7.5.0","info"],"pid":6,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["info","task_manager"],"pid":6,"message":"Initialising Task Manager with UUID: 59954ab1-8253-4eda-b13e-296b7d279956"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:task_manager@7.5.0","info"],"pid":6,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:rollup@7.5.0","info"],"pid":6,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:transform@7.5.0","info"],"pid":6,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["info","siem"],"pid":6,"message":"Plugin initializing"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["info","siem"],"pid":6,"message":"Plugin done initializing"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:siem@7.5.0","info"],"pid":6,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:remote_clusters@7.5.0","info"],"pid":6,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:cross_cluster_replication@7.5.0","info"],"pid":6,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:upgrade_assistant@7.5.0","info"],"pid":6,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:uptime@7.5.0","info"],"pid":6,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:oss_telemetry@7.5.0","info"],"pid":6,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:file_upload@7.5.0","info"],"pid":6,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["warning","encrypted_saved_objects"],"pid":6,"message":"Generating a random key for xpack.encrypted_saved_objects.encryptionKey. To be able to decrypt encrypted saved objects attributes after restart, please set xpack.encrypted_saved_objects.encryptionKey in kibana.yml"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:encrypted_saved_objects@7.5.0","info"],"pid":6,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:data@7.5.0","info"],"pid":6,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:lens@7.5.0","info"],"pid":6,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["status","plugin:snapshot_restore@7.5.0","info"],"pid":6,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["fatal","root"],"pid":6,"message":"TypeError: Cannot read property 'name' of undefined\n    at Plugin.init [as externalInit] (/usr/share/kibana/plugins/keycloak-kibana/index.js:210:40)\n    at Object.register (/usr/share/kibana/src/legacy/server/plugins/lib/plugin.js:96:20)\n    at internals.Server.register (/usr/share/kibana/node_modules/hapi/lib/server.js:431:35)\n    at Plugin.init (/usr/share/kibana/src/legacy/server/plugins/lib/plugin.js:100:28)\n    at Plugin.init (/usr/share/kibana/node_modules/lodash/index.js:7411:25)\n    at callPluginHook (/usr/share/kibana/src/legacy/server/plugins/lib/call_plugin_hook.js:53:25)"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["info","plugins-system"],"pid":6,"message":"Stopping all plugins."}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["info","plugins","data"],"pid":6,"message":"Stopping plugin"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["info","plugins","translations"],"pid":6,"message":"Stopping plugin"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["info","plugins","spaces"],"pid":6,"message":"Stopping plugin"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["info","plugins","features"],"pid":6,"message":"Stopping plugin"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["info","plugins","timelion"],"pid":6,"message":"Stopping plugin"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["info","plugins","licensing"],"pid":6,"message":"Stopping plugin"}
{"type":"log","@timestamp":"2020-03-12T08:35:20Z","tags":["info","plugins","code"],"pid":6,"message":"Stopping plugin"}

 FATAL  TypeError: Cannot read property 'name' of undefined
```

**Comment by Finu** [comment]
Hi.
Could you try to run kibana with `logging.verbose: true` maybe there gonna be some additional information. Because this one does not give much clue.

**Comment by prasus** [comment]
Thank you @Finu for the response.  Please find the logs after enabling Kibana verbose logging. unfortunately, I couldn't figure out any good pointers from these messages 🙁 

```
{"type":"log","@timestamp":"2020-03-16T05:23:37Z","tags":["plugins","debug"],"pid":6,"plugin":{"name":"keycloak-kibana","version":"3.2.0","description":"A Keycloak authorization plugin for Kibana","main":"index.js","license":"Apache-2.0","kibana":{"version":"7.5.0","templateVersion":"1.0.0"},"dependencies":{"axios":"^0.18.0","keycloak-connect":"^4.0.0","keycloak-hapi":"^1.2.0","lodash":"npm:@elastic/lodash@3.10.1-kibana3","url-join":"^4.0.0","yar":"^9.1.0"},"build":{"git":{"count":"111","sha":"e60a0fe","date":"Wed, 11 Mar 2020 10:36:16 +0100"},"date":"Thu Mar 12 2020 06:09:14 GMT+0000 (Coordinated Universal Time)"}},"message":"Initializing plugin keycloak-kibana@3.2.0"}
{"type":"log","@timestamp":"2020-03-16T05:23:37Z","tags":["debug","root"],"pid":6,"message":"shutting root down"}
{"type":"log","@timestamp":"2020-03-16T05:23:37Z","tags":["fatal","root"],"pid":6,"message":"TypeError: Cannot read property 'name' of undefined\n    at Plugin.init [as externalInit] (/usr/share/kibana/plugins/keycloak-kibana/index.js:210:40)\n    at Object.register (/usr/share/kibana/src/legacy/server/plugins/lib/plugin.js:96:20)\n    at internals.Server.register (/usr/share/kibana/node_modules/hapi/lib/server.js:431:35)\n    at Plugin.init (/usr/share/kibana/src/legacy/server/plugins/lib/plugin.js:100:28)\n    at Plugin.init (/usr/share/kibana/node_modules/lodash/index.js:7411:25)\n    at callPluginHook (/usr/share/kibana/src/legacy/server/plugins/lib/call_plugin_hook.js:53:25)"}
{"type":"log","@timestamp":"2020-03-16T05:23:37Z","tags":["debug","server"],"pid":6,"message":"stopping server"}
{"type":"log","@timestamp":"2020-03-16T05:23:37Z","tags":["debug","legacy-service"],"pid":6,"message":"stopping legacy service"}
{"type":"log","@timestamp":"2020-03-16T05:23:37Z","tags":["debug","plugins-service"],"pid":6,"message":"Stopping plugins service"}
{"type":"log","@timestamp":"2020-03-16T05:23:37Z","tags":["info","plugins-system"],"pid":6,"message":"Stopping all plugins."}
{"type":"log","@timestamp":"2020-03-16T05:23:37Z","tags":["debug","plugins-system"],"pid":6,"message":"Stopping plugin \"data\"..."}
{"type":"log","@timestamp":"2020-03-16T05:23:37Z","tags":["info","plugins","data"],"pid":6,"message":"Stopping plugin"}
{"type":"log","@timestamp":"2020-03-16T05:23:37Z","tags":["debug","plugins-system"],"pid":6,"message":"Stopping plugin \"translations\"..."}
{"type":"log","@timestamp":"2020-03-16T05:23:37Z","tags":["info","plugins","translations"],"pid":6,"message":"Stopping plugin"}
{"type":"log","@timestamp":"2020-03-16T05:23:37Z","tags":["debug","plugins-system"],"pid":6,"message":"Stopping plugin \"spaces\"..."}
{"type":"log","@timestamp":"2020-03-16T05:23:37Z","tags":["info","plugins","spaces"],"pid":6,"message":"Stopping plugin"}
{"type":"log","@timestamp":"2020-03-16T05:23:37Z","tags":["debug","plugins-system"],"pid":6,"message":"Stopping plugin \"features\"..."}
{"type":"log","@timestamp":"2020-03-16T05:23:37Z","tags":["info","plugins","features"],"pid":6,"message":"Stopping plugin"}
{"type":"log","@timestamp":"2020-03-16T05:23:37Z","tags":["debug","plugins","features"],"pid":6,"message":"Stopping plugin"}
{"type":"log","@timestamp":"2020-03-16T05:23:37Z","tags":["debug","plugins-system"],"pid":6,"message":"Stopping plugin \"timelion\"..."}
{"type":"log","@timestamp":"2020-03-16T05:23:37Z","tags":["info","plugins","timelion"],"pid":6,"message":"Stopping plugin"}
{"type":"log","@timestamp":"2020-03-16T05:23:37Z","tags":["debug","plugins","timelion"],"pid":6,"message":"Stopping plugin"}
{"type":"log","@timestamp":"2020-03-16T05:23:37Z","tags":["debug","plugins-system"],"pid":6,"message":"Stopping plugin \"code\"..."}
{"type":"log","@timestamp":"2020-03-16T05:23:37Z","tags":["info","plugins","code"],"pid":6,"message":"Stopping plugin"}
{"type":"log","@timestamp":"2020-03-16T05:23:37Z","tags":["debug","plugins-system"],"pid":6,"message":"Stopping plugin \"licensing\"..."}
{"type":"log","@timestamp":"2020-03-16T05:23:37Z","tags":["info","plugins","licensing"],"pid":6,"message":"Stopping plugin"}
{"type":"log","@timestamp":"2020-03-16T05:23:37Z","tags":["debug","elasticsearch-service"],"pid":6,"message":"Stopping elasticsearch service"}
{"type":"log","@timestamp":"2020-03-16T05:23:37Z","tags":["debug","elasticsearch-service"],"pid":6,"message":"Closing elasticsearch clients"}
{"type":"log","@timestamp":"2020-03-16T05:23:37Z","tags":["debug","http","server","Kibana"],"pid":6,"message":"stopping http server"}

 FATAL  TypeError: Cannot read property 'name' of undefined
```

**Comment by aarranz** [comment]
Hi all!

I see that you are not providing a value for the `keycloak.session.cookieOptions.password` property. I'm currently trying to use this plugin and I have made a lot of changes on my configuration but I think that I have solved this problem by setting that property.
